= Hi there 👋
My name is ArwynFr and I am a senior software architect in 🇫🇷 France.

Here are some projets I am working on or have been working on:

== Pwsh modules
[horizontal]
https://github.com/ArwynFr/pwsh-ConventionalCommits[Conventional Commits]:: Checks wether a git commit message follows conventional commits and parse the message into a stucture
https://github.com/ArwynFr/pwsh-ConventionalVersioning[Conventional Versioning]:: Used to version a GitHub repo based on CC conventions and semver
https://github.com/ArwynFr/pwsh-HashWebCopy[HashWebCopy]:: Directory syncing over https ; my personnal rsync alternative
https://github.com/ArwynFr/pwsh-StepSemVer[StepSemVer]:: A QOL addition to the semver pwsh structure

== Github actions

[horizontal]
https://github.com/team-gsri/actions-arma-tools[arma 3 tools]:: Runs arma 3 tools in order to build and publish missions or addons to GtiHub and Steam
https://github.com/ArwynFr/actions-docker-context[docker context]:: Provide SSH access to remote docker host in a Github workflow
https://github.com/ArwynFr/actions-conventional-versioning[conventional versioning]:: Automatically create a semver release of your project

== Other

[horizontal]
https://github.com/ArwynFr/AspectNetSharp[AspectNetSharp]:: A lightweight AOP library for .NET Framework
https://github.com/ArwynFr/docker-tools[docker tools]:: Small utils for docker admins, does stuff like volume backup/restore
https://github.com/ArwynFr/homepage[homepage]:: My personnal webpage ; used to experiment with agent-based deployment
VaReg (project):: A public service for virtual aircraft and airline registration for flight simmers
