name: Deploy a docker application to a kubernetes cluster

on:
  workflow_call:
    inputs:
      version:
        description: Application version number in semver format
        required: true
        type: string
      context:
        description: Path to the docker context directory
        required: true
        type: string
      resources:
        description: Path to the kubernetes resources directory
        required: true
        type: string
      image:
        description: Name of the kubernetes image spec to replace
        default: app
        required: false
        type: string
    secrets:
      server:
        description: URL of the Kubernetes cluster server
        required: true
      authority:
        description: CA certificate of the cluster, base64 encoded
        required: true
      token:
        description: JWT token of the ServiceAccount used for deployment
        required: true

env:
  image: ghcr.io/${{ github.repository }}:${{ inputs.version }}
  # use ${image,,} bash expansion to lowercase the image name
  # otherwise, pushing will fail if the repo has uppercase chars

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build --tag ${image,,} ${{ inputs.context }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to the registry
        run: docker push ${image,,}

      - name: Kustomize image tag
        run: (cd ${{ inputs.resources }} && kustomize edit set image ${{ inputs.image }}=${image,,})

      - name: Authenticate to the kubernetes cluster
        uses: arwynfr/arwynfr/.github/actions/kubernetes-auth@main
        with:
          token: ${{ secrets.token }}
          server: ${{ secrets.server }}
          authority: ${{ secrets.authority }}

      - name: Apply ressources on the cluster
        run: kubectl apply -k ${{ inputs.resources }}

      - name: Logout from the Kubernetes cluster
        run: |
          kubectl config delete-context default
          kubectl config delete-user default
          kubectl config delete-cluster default
